# Sep 22, 2019 Eigen Decomposition
* name: Jikhan Jeong
* ref: https://www.edwith.org/linearalgebra4ai/lecture/25098/

In [3]:
import numpy as np
import numpy.linalg as la
from numpy.linalg import eig
from numpy.linalg import inv

import time

In [28]:
# diagonalization and power of a matrix
A = np.array([[4, 0, -2], [2, 5, 4], [0, 0, 5]])
A

array([[ 4,  0, -2],
       [ 2,  5,  4],
       [ 0,  0,  5]])

# Eig(set) = eigen value, eigen vector
* from numpy.linalg import eig

In [29]:
eig_val, eig_vec = eig(A)
eig_val

array([5., 4., 5.])

In [30]:
eig_vec = eig(A)
eig_vec
# column 1 is a eigen vector of elgenvalue 5
# column 2 is a eigen vector of elgenvalue 4
# column 3 is a eigen vector of elgenvalue 5

(array([5., 4., 5.]), array([[ 0.        ,  0.4472136 , -0.89442719],
        [ 1.        , -0.89442719,  0.        ],
        [ 0.        ,  0.        ,  0.4472136 ]]))

# $A = VDV^{-1}$
* D = np.diag(eigen value)

In [12]:
D = np.diag(eig_val)
D

array([[5., 0., 0.],
       [0., 4., 0.],
       [0., 0., 5.]])

In [13]:
V = eig_vec
V

array([[ 0.        ,  0.4472136 , -0.89442719],
       [ 1.        , -0.89442719,  0.        ],
       [ 0.        ,  0.        ,  0.4472136 ]])

# $T(x)= Ax = VDV_{-1}x = V(D(V^{-1}x))$
* interse matrix = la.inv

In [14]:
V.dot(D).dot(la.inv(V))  # = A

array([[ 4.,  0., -2.],
       [ 2.,  5.,  4.],
       [ 0.,  0.,  5.]])

# $A^{5}$

In [15]:
la.matrix_power(A,5)

array([[ 1024,     0, -4202],
       [ 4202,  3125,  8404],
       [    0,     0,  3125]])

# $D^{5}$

In [16]:
D_power_5 = np.diag(eig_val**5)
D_power_5

array([[3125.,    0.,    0.],
       [   0., 1024.,    0.],
       [   0.,    0., 3125.]])

# $A^{5} = VD^{5}V^{-1}$

In [19]:
V.dot(D_power_5).dot(la.inv(V)) # V^5

array([[ 1024.,     0., -4202.],
       [ 4202.,  3125.,  8404.],
       [    0.,     0.,  3125.]])

# Time Check in two different wasy for eigen value    
# decomposition
# $A^{k}x = VD^{k}V^{-1}x$

In [33]:
x = np.random.rand(5)
x

array([0.43649489, 0.82271485, 0.50183461, 0.94555263, 0.64509335])

In [24]:
# create a matrix A to make eigen matrix is possible.

A = np.array([[4., 4, 2, 3, -2], [0, 1, -2, -2, 2], [6, 12, 11, 2, -4], [9, 20, 10, 10, -6], [15, 28, 14, 5, -3]])

A = A + A.T # symmetric
A = A/np.expand_dims(np.sum(A, 1), axis = 1)
print ('A : ', A)

# initialize parameters
x = np.random.rand(5)
n_times = 1000000

# perform matrix multiplications
y = x
start_time = time.time()
for i in range(0, n_times):
    y = A.dot(y)
end_time = time.time()
elapse_time = end_time - start_time
print ('y: ', y)
print ('elapse_time : ', elapse_time)

A :  [[ 0.17777778  0.08888889  0.17777778  0.26666667  0.28888889]
 [ 0.0625      0.03125     0.15625     0.28125     0.46875   ]
 [ 0.12903226  0.16129032  0.35483871  0.19354839  0.16129032]
 [ 0.19672131  0.29508197  0.19672131  0.32786885 -0.01639344]
 [ 0.2826087   0.65217391  0.2173913  -0.02173913 -0.13043478]]
y:  [0.44130873 0.44130873 0.44130873 0.44130873 0.44130873]
elapse_time :  1.046462059020996


# Eig(set) = eigen value, eigen vector
* from numpy.linalg import eig
* la.solve(V,x), $a =V^{-1}x, where Va = x$
* '*' : element wise 

In [25]:
eig_val, eig_vec = eig(A)
D = np.diag(eig_val)
V = eig_vec

# perform matrix multiplications using eigendecomposition
start_time = time.time()
y = V.dot((eig_val**n_times)*la.solve(V,x))
end_time = time.time()
elapse_time = end_time - start_time
print ('y: ', y)
print ('elapse_time : ', elapse_time)

y:  [0.44130873 0.44130873 0.44130873 0.44130873 0.44130873]
elapse_time :  0.0010311603546142578
